apiVersion: v1
kind: Pod
metadata:
  name: kuard-res-XX
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources:
      requests:
        memory: ""
        cpu: ""
      limits:
        memory: ""
        cpu: ""